### ISSUE TITLE
Sosyal medya paylaşımları eklenmeli

### ISSUE THREAD

**Issue by bulutfon** [bulutfon/ozelpaket#1]
- Facebook
- Twitter
- Linkedin
- Email günder

Üçüncü parti bir servis kullanılabilir. Paylaşım adetleri gözükürse iyi olur.

![screen shot 2015-06-23 at 06 25 43](https://cloud.githubusercontent.com/assets/5015297/8298376/b70e0fd8-1970-11e5-90f7-a285ad0dbcb7.png)

**Comment by coskuntekin** [comment]
Open graph tag lari eklendi ama live preview yapamadim zira linki yayindaki siteden aliyor. Birde @onurozgurozkan image ekleyecektik.

**Comment by onurozgurozkan** [comment]
![lawoud-bulutfon-hizliceviri](https://cloud.githubusercontent.com/assets/248897/8346196/b6b3de5e-1b01-11e5-87fa-7d39099bf86b.png)

**Comment by onurozgurozkan** [comment]
@coskuntekin resmi ekledim. Benzer birde issue açtım #10 scrolldan dolayı paylaşım alanı gözükmüyor. Onu çözmek lazım.

**Comment by onurozgurozkan** [comment]
@coskuntekin  http://avukatlara.ozelpaket.net/assets/images/avukatlara-ozel-paket.png linki çalışmıyor. og taglarinde hata var!

**Comment by coskuntekin** [comment]
@onurozgurozkan buradan kontrol edilebilir. https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Favukatlara.ozelpaket.net%2F
