### ISSUE TITLE
Scrolldan dolayı maalesef paylaşım buttonları gözükmüyor. Bu UX ve Conversation açısından ciddi problem. 

### ISSUE THREAD

**Issue by onurozgurozkan** [bulutfon/ozelpaket#10]
![screen shot 2015-06-25 at 06 37 05](https://cloud.githubusercontent.com/assets/248897/8346404/c38b17e8-1b04-11e5-95ea-95490498196d.png)

**Comment by onurozgurozkan** [comment]
@coskuntekin bu konuyu nasıl çözebiliriz? Share buttonlarını sağa alalım diyorum lakin bu sseferde mobilde sorun çıkacak?

**Comment by coskuntekin** [comment]
margin lerle cozum uretebilirim ama emin degilim @onurozgurozkan sayfanin altina sticky yapabiliriz ya da sagda sticky sekilde kalabilir mobile sticky kaldiririz Ama o zamanda extra bi layout yapmak lazim.
