### ISSUE TITLE
Linkler anlaşılmıyor ve karışık.

### ISSUE THREAD

**Issue by bulutfon** [bulutfon/ozelpaket#4]
Mevcut hali yerine http://startups.paddle.com/ sitesindeki gibi olmalı.
- Mevcuttaki beyaz alanın üzerine gelince başka bir panel gözükmeli.
- Bu alanda aşağıdaki gri bilgiler olmalı ve farklı bir renkle "Paketten Yararlan >>" linki olmalı ve link olduğu belli olmalı. '>>' gibi bir simge link olduğunu vurguluyor.

![ao](https://cloud.githubusercontent.com/assets/5015297/8298479/06fa9dee-1972-11e5-88a9-a2c30d18ab30.gif)

**Comment by bulutfon** [comment]
"İçeriğe göz at" yerine "Paketten Yararlanın >>" yazılsın. Birde yeşil bar okunmuyor, ortalanıp daha uzun olursa iyi olur.

**Comment by coskuntekin** [comment]
Link textini image da yapabiliriz referans sitede oldugu uzre. Review yapip bildirir misin abi? @onurozgurozkan

**Comment by coskuntekin** [comment]
text-shadow la guclendirmeyi denicem. Zira tekrar baktigimda bu hali cok zayif geldi
